/**
 * Demo / fallback data for the LLM Regression Detector dashboard.
 * Used when the backend returns empty data (has_data: false) or
 * when API calls fail (e.g. frontend-only Vercel deploy).
 *
 * All numbers are deterministic so the demo is stable across reloads.
 */

const ts = (daysAgo) => {
  const d = new Date()
  d.setDate(d.getDate() - daysAgo)
  return d.toISOString()
}

// ---------- Runs ----------
export const DEMO_RUNS = [
  {
    run_id: 'run-demo-v1-openai',
    prompt_version: 'v1',
    provider: 'openai',
    model: 'gpt-4o-mini',
    status: 'PASS',
    overall_accuracy: 68.3,
    total_cases: 60,
    passed_cases: 41,
    failed_cases: 19,
    regressions: 0,
    avg_latency_ms: 420,
    avg_tokens: 285,
    avg_cost_usd: 0.0043,
    avg_summary_relevance: 3.2,
    category_accuracy: { billing: 60, technical: 72, complaint: 65, general: 76 },
    timestamp: ts(42),
    baseline_run_id: null,
  },
  {
    run_id: 'run-demo-v2-openai',
    prompt_version: 'v2',
    provider: 'openai',
    model: 'gpt-4o-mini',
    status: 'PASS',
    overall_accuracy: 71.7,
    total_cases: 60,
    passed_cases: 43,
    failed_cases: 17,
    regressions: 1,
    avg_latency_ms: 395,
    avg_tokens: 278,
    avg_cost_usd: 0.0042,
    avg_summary_relevance: 3.4,
    category_accuracy: { billing: 66, technical: 74, complaint: 68, general: 78 },
    timestamp: ts(35),
    baseline_run_id: 'run-demo-v1-openai',
  },
  {
    run_id: 'run-demo-v3-openai',
    prompt_version: 'v3',
    provider: 'openai',
    model: 'gpt-4o-mini',
    status: 'WARNING',
    overall_accuracy: 70.0,
    total_cases: 60,
    passed_cases: 42,
    failed_cases: 18,
    regressions: 3,
    avg_latency_ms: 405,
    avg_tokens: 290,
    avg_cost_usd: 0.0044,
    avg_summary_relevance: 3.3,
    category_accuracy: { billing: 63, technical: 73, complaint: 67, general: 77 },
    timestamp: ts(28),
    baseline_run_id: 'run-demo-v2-openai',
  },
  {
    run_id: 'run-demo-v4-openai',
    prompt_version: 'v4',
    provider: 'openai',
    model: 'gpt-4o-mini',
    status: 'PASS',
    overall_accuracy: 76.7,
    total_cases: 60,
    passed_cases: 46,
    failed_cases: 14,
    regressions: 0,
    avg_latency_ms: 380,
    avg_tokens: 270,
    avg_cost_usd: 0.0041,
    avg_summary_relevance: 3.7,
    category_accuracy: { billing: 73, technical: 80, complaint: 72, general: 82 },
    timestamp: ts(21),
    baseline_run_id: 'run-demo-v3-openai',
  },
  {
    run_id: 'run-demo-v5-openai',
    prompt_version: 'v5',
    provider: 'openai',
    model: 'gpt-4o-mini',
    status: 'PASS',
    overall_accuracy: 80.0,
    total_cases: 60,
    passed_cases: 48,
    failed_cases: 12,
    regressions: 1,
    avg_latency_ms: 365,
    avg_tokens: 260,
    avg_cost_usd: 0.0039,
    avg_summary_relevance: 3.9,
    category_accuracy: { billing: 76, technical: 84, complaint: 76, general: 84 },
    timestamp: ts(14),
    baseline_run_id: 'run-demo-v4-openai',
  },
  {
    run_id: 'run-demo-v6-openai',
    prompt_version: 'v6',
    provider: 'openai',
    model: 'gpt-4o-mini',
    status: 'PASS',
    overall_accuracy: 83.3,
    total_cases: 60,
    passed_cases: 50,
    failed_cases: 10,
    regressions: 0,
    avg_latency_ms: 350,
    avg_tokens: 255,
    avg_cost_usd: 0.0038,
    avg_summary_relevance: 4.1,
    category_accuracy: { billing: 80, technical: 86, complaint: 80, general: 87 },
    timestamp: ts(7),
    baseline_run_id: 'run-demo-v5-openai',
  },
  {
    run_id: 'run-demo-v7-openai',
    prompt_version: 'v7',
    provider: 'openai',
    model: 'gpt-4o-mini',
    status: 'PASS',
    overall_accuracy: 86.7,
    total_cases: 60,
    passed_cases: 52,
    failed_cases: 8,
    regressions: 0,
    avg_latency_ms: 340,
    avg_tokens: 248,
    avg_cost_usd: 0.0037,
    avg_summary_relevance: 4.3,
    category_accuracy: { billing: 84, technical: 90, complaint: 82, general: 91 },
    timestamp: ts(3),
    baseline_run_id: 'run-demo-v6-openai',
  },
  {
    run_id: 'run-demo-v8-openai',
    prompt_version: 'v8',
    provider: 'openai',
    model: 'gpt-4o-mini',
    status: 'FAIL',
    overall_accuracy: 78.3,
    total_cases: 60,
    passed_cases: 47,
    failed_cases: 13,
    regressions: 5,
    avg_latency_ms: 390,
    avg_tokens: 295,
    avg_cost_usd: 0.0044,
    avg_summary_relevance: 3.6,
    category_accuracy: { billing: 73, technical: 82, complaint: 74, general: 84 },
    timestamp: ts(1),
    baseline_run_id: 'run-demo-v7-openai',
  },
  {
    run_id: 'run-demo-v8-anthropic',
    prompt_version: 'v8',
    provider: 'anthropic',
    model: 'claude-sonnet-4-20250514',
    status: 'WARNING',
    overall_accuracy: 81.7,
    total_cases: 60,
    passed_cases: 49,
    failed_cases: 11,
    regressions: 3,
    avg_latency_ms: 520,
    avg_tokens: 310,
    avg_cost_usd: 0.0062,
    avg_summary_relevance: 4.0,
    category_accuracy: { billing: 78, technical: 85, complaint: 79, general: 84 },
    timestamp: ts(1),
    baseline_run_id: 'run-demo-v7-openai',
  },
  {
    run_id: 'run-demo-v8-gemini',
    prompt_version: 'v8',
    provider: 'gemini',
    model: 'gemini-2.5-flash',
    status: 'PASS',
    overall_accuracy: 85.0,
    total_cases: 60,
    passed_cases: 51,
    failed_cases: 9,
    regressions: 1,
    avg_latency_ms: 290,
    avg_tokens: 240,
    avg_cost_usd: 0.0029,
    avg_summary_relevance: 4.2,
    category_accuracy: { billing: 82, technical: 88, complaint: 81, general: 89 },
    timestamp: ts(0),
    baseline_run_id: 'run-demo-v7-openai',
  },
]


// ---------- Overview ----------
export const DEMO_OVERVIEW = {
  has_data: true,
  latest: DEMO_RUNS[DEMO_RUNS.length - 3], // v8 openai (FAIL)
  baseline: DEMO_RUNS[DEMO_RUNS.length - 4], // v7
  comparison: {
    overall_accuracy_delta: -8.4,
    category_accuracy_delta: { billing: -11, technical: -8, complaint: -8, general: -7 },
    no_change_count: 39,
    p_value: 0.003,
    statistically_significant: true,
    status: 'FAIL',
  },
  regressions: [
    {
      case_id: 'case_017',
      input: 'Hi, I was charged $49.99 twice for my Pro subscription last month. Could you refund the duplicate charge?',
      expected_category: 'billing',
      previous_category: 'billing',
      new_category: 'general',
      previous_summary_score: 4.2,
      new_summary_score: 2.8,
      previous_summary: 'Customer reports duplicate charge of $49.99 on Pro subscription and requests a refund for the extra billing.',
      new_summary: 'Customer has a question about their account charges.',
      verdict: 'The new version lost specificity: it failed to identify the core issue (duplicate charge) and the specific amount ($49.99). The classification shifted from billing to general, missing the clear billing intent.',
      confidence_delta: -18.5,
      latency_delta: 45,
      tokens_delta: 12,
      summary_score_delta: -1.4,
    },
    {
      case_id: 'case_023',
      input: 'My API integration keeps throwing 429 rate-limit errors after the latest update. We are on the Enterprise plan with 10k RPM.',
      expected_category: 'technical',
      previous_category: 'technical',
      new_category: 'complaint',
      previous_summary_score: 4.5,
      new_summary_score: 3.1,
      previous_summary: 'Enterprise customer experiencing 429 rate-limit errors post-update despite 10k RPM allocation. Likely a regression in rate-limit enforcement.',
      new_summary: 'Customer is upset about errors in their API usage after a recent change.',
      verdict: 'Classification regressed from technical to complaint. The new response loses critical details: the specific error code (429), the plan tier (Enterprise), and the RPM quota (10k). Framing shifted from diagnostic to emotional.',
      confidence_delta: -22.0,
      latency_delta: 30,
      tokens_delta: -5,
      summary_score_delta: -1.4,
    },
    {
      case_id: 'case_031',
      input: 'I want to cancel my subscription immediately. Your support has been terrible and I\'ve been waiting 3 days for a response.',
      expected_category: 'complaint',
      previous_category: 'complaint',
      new_category: 'billing',
      previous_summary_score: 4.0,
      new_summary_score: 2.5,
      previous_summary: 'Frustrated customer requesting immediate cancellation due to poor support response times (3-day wait). Churn risk — escalate.',
      new_summary: 'Customer wants to change their subscription settings.',
      verdict: 'Critical miss: the emotional urgency and churn risk were completely lost. Classification shifted to billing (technically not wrong for cancellation) but misses the primary signal — this is a complaint driven by poor support experience.',
      confidence_delta: -15.0,
      latency_delta: 55,
      tokens_delta: 20,
      summary_score_delta: -1.5,
    },
    {
      case_id: 'case_042',
      input: 'Is there a way to export my dashboard data as CSV? I need it for our quarterly board report by Friday.',
      expected_category: 'technical',
      previous_category: 'technical',
      new_category: 'general',
      previous_summary_score: 4.3,
      new_summary_score: 3.0,
      previous_summary: 'Customer requesting CSV export functionality for dashboard data with a Friday deadline for a board report. Check if export feature is available or provide workaround.',
      new_summary: 'Customer asking about data export options.',
      verdict: 'Lost the urgency (Friday deadline), the purpose (board report), and the specific format (CSV). Classification dropped from technical to general.',
      confidence_delta: -12.0,
      latency_delta: 20,
      tokens_delta: 8,
      summary_score_delta: -1.3,
    },
    {
      case_id: 'case_055',
      input: 'Our team of 15 needs to upgrade from Starter to Business plan. Can we get a volume discount and migrate our existing data?',
      expected_category: 'billing',
      previous_category: 'billing',
      new_category: 'general',
      previous_summary_score: 4.1,
      new_summary_score: 2.9,
      previous_summary: 'Team of 15 requesting Starter→Business upgrade with volume discount inquiry and data migration requirements. Upsell opportunity.',
      new_summary: 'Customer wants to know about plan options.',
      verdict: 'Lost critical details: team size (15), current plan (Starter), target plan (Business), volume discount request, and data migration concern. High-value upsell signal completely missed.',
      confidence_delta: -14.0,
      latency_delta: 35,
      tokens_delta: 15,
      summary_score_delta: -1.2,
    },
  ],
  improvements: [
    {
      case_id: 'case_008',
      input: 'Thank you for resolving my issue so quickly! The new dashboard looks amazing.',
      expected_category: 'general',
      previous_category: 'complaint',
      new_category: 'general',
      previous_summary_score: 2.0,
      new_summary_score: 4.0,
    },
    {
      case_id: 'case_044',
      input: 'Can you walk me through setting up SSO with our Okta instance?',
      expected_category: 'technical',
      previous_category: 'general',
      new_category: 'technical',
      previous_summary_score: 2.5,
      new_summary_score: 4.2,
    },
  ],
  drift: {
    is_drifting: true,
    current_moving_avg: 80.7,
    reference_avg: 86.7,
    delta_pct: -6.0,
    window: 7,
    message: 'Performance drift detected: 7-run moving average (80.7%) is 6.0 pts below the reference average (86.7%). Investigate prompt v8 regressions.',
  },
  total_runs: 10,
}


// ---------- Cases for latest run (v8 openai) ----------
const CATEGORIES = ['billing', 'technical', 'complaint', 'general']
const CASE_INPUTS = [
  { id: 'case_001', input: 'I was charged $49.99 twice for my Pro subscription last month. Can you refund the duplicate?', cat: 'billing', passed: false },
  { id: 'case_002', input: 'My API integration keeps returning 429 rate-limit errors after the latest SDK update.', cat: 'technical', passed: true },
  { id: 'case_003', input: 'I want to cancel my subscription immediately. Your support has been terrible.', cat: 'complaint', passed: false },
  { id: 'case_004', input: 'Can you walk me through setting up SSO with our Okta instance?', cat: 'technical', passed: true },
  { id: 'case_005', input: 'Thank you for resolving my issue so quickly! The new dashboard looks great.', cat: 'general', passed: true },
  { id: 'case_006', input: 'Our invoice from March is showing the wrong tax rate. We are a tax-exempt organization.', cat: 'billing', passed: true },
  { id: 'case_007', input: 'The webhook endpoint is timing out after 5 seconds consistently. Need help debugging.', cat: 'technical', passed: true },
  { id: 'case_008', input: 'This is the third time my support ticket has been ignored. Escalate this now.', cat: 'complaint', passed: true },
  { id: 'case_009', input: 'What are your business hours for phone support?', cat: 'general', passed: true },
  { id: 'case_010', input: 'We need to upgrade our team from 5 to 25 seats. Any volume discounts?', cat: 'billing', passed: false },
  { id: 'case_011', input: 'Getting a CORS error when calling the /api/v2/users endpoint from our React app.', cat: 'technical', passed: true },
  { id: 'case_012', input: 'Your product quality has declined significantly in the last 3 months.', cat: 'complaint', passed: true },
  { id: 'case_013', input: 'Is there a way to export dashboard data as CSV for our board report?', cat: 'technical', passed: false },
  { id: 'case_014', input: 'Can I get a breakdown of our usage charges for Q2?', cat: 'billing', passed: true },
  { id: 'case_015', input: 'How do I reset my 2FA if I lost my authenticator device?', cat: 'technical', passed: true },
]

export const DEMO_CASES = CASE_INPUTS.map((c, i) => ({
  case_id: c.id,
  run_id: 'run-demo-v8-openai',
  input: c.input,
  expected_category: c.cat,
  actual_category: c.passed ? c.cat : CATEGORIES[(CATEGORIES.indexOf(c.cat) + 1) % CATEGORIES.length],
  category_match: c.passed,
  passed: c.passed,
  confidence: c.passed ? 82 + (i % 15) : 45 + (i % 20),
  latency_ms: 280 + (i * 17) % 200,
  tokens_used: 200 + (i * 23) % 150,
  cost_usd: 0.003 + (i * 0.0004) % 0.003,
  summary_score: c.passed ? 3.8 + (i % 5) * 0.2 : 2.0 + (i % 4) * 0.3,
  expected_summary: `Expected summary for ${c.id}: properly categorized as ${c.cat} with relevant details extracted.`,
  actual_summary: c.passed
    ? `Correctly identified as ${c.cat}. Key details extracted including specific entities and action items.`
    : `Misclassified — lost important context. Categorized as ${CATEGORIES[(CATEGORIES.indexOf(c.cat) + 1) % CATEGORIES.length]} instead of ${c.cat}.`,
  judge_rationale: c.passed
    ? 'The model correctly identified the category and extracted key entities. Summary captures the main intent and relevant details.'
    : 'Category mismatch: the model missed the primary signal in the input. Summary lost specificity and key details compared to the expected output.',
  failure_reason: c.passed ? null : 'Category mismatch',
  failure_explanation: c.passed
    ? '✅ Category matched, summary quality above threshold.'
    : `❌ Expected category "${c.cat}" but got "${CATEGORIES[(CATEGORIES.indexOf(c.cat) + 1) % CATEGORIES.length]}". Summary lost key details.`,
}))


// ---------- Drift ----------
export const DEMO_DRIFT = {
  runs: DEMO_RUNS,
  drift: DEMO_OVERVIEW.drift,
}


// ---------- Meta ----------
export const DEMO_META = {
  mock_mode: true,
  llm_model: 'gpt-4o-mini',
  llm_provider: 'openai',
  judge_model: 'gpt-4o-mini',
  judge_provider: 'openai',
  supported_providers: ['openai', 'anthropic', 'gemini'],
  provider_availability: { openai: true, anthropic: true, gemini: true },
  semantic_similarity_enabled: false,
  warning_threshold_pct: 3.0,
  critical_threshold_pct: 8.0,
  drift_window: 7,
  drift_threshold_pct: 5.0,
  slack_configured: false,
  discord_configured: false,
  email_configured: false,
  rubric: {},
}


// ---------- Helper: wrap api to use demo data as fallback ----------
export function withDemoFallback(apiCall, demoData) {
  return apiCall.catch(() => demoData)
}
